---
output: 
  html_document: 
    fig_width: 13
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 13,
  fig.height = 7,
  fig.align = "center"
)
```

```{r}
library(dplyr)
library(tidyr)
library(readr)
library(DESeq2)
library(ggplot2)
library(patchwork)
library(reshape2)
set.seed(42)
```

```{r}
astrocyte_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/astrocyte/astrocyte_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
caudal_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/caudalganglioniceminencederivedGABAergiccorticalinterneuron/caudalganglioniceminencederivedGABAergiccorticalinterneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
chandelier_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/chandelierpvalbGABAergiccorticalinterneuron/chandelierpvalbGABAergiccorticalinterneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
endothelial_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/endothelialcell/endothelialcell_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L2_36_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/L2_3.6intratelencephalicprojectingglutamatergicneuron/L2_3.6intratelencephalicprojectingglutamatergicneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L5_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/L5extratelencephalicprojectingglutamatergiccorticalneuron/L5extratelencephalicprojectingglutamatergiccorticalneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L6bGlut_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/L6bglutamatergiccorticalneuron/L6bglutamatergiccorticalneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L6CT_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/L6corticothalamic.projectingglutamatergiccorticalneuron/L6corticothalamic.projectingglutamatergiccorticalneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
lamp5_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/lamp5GABAergiccorticalinterneuron/lamp5GABAergiccorticalinterneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
microglia_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/microglialcell/microglialcell_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
NPglut_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/near.projectingglutamatergiccorticalneuron/near.projectingglutamatergiccorticalneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
oligo_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/oligodendrocyte/oligodendrocyte_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
oligoPC_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/oligodendrocyteprecursorcell/oligodendrocyteprecursorcell_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
pvalbGABA_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/pvalbGABAergiccorticalinterneuron/pvalbGABAergiccorticalinterneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
sncg_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/sncgGABAergiccorticalinterneuron/sncgGABAergiccorticalinterneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
sstGABA_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/sstGABAergiccorticalinterneuron/sstGABAergiccorticalinterneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
VLMC_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/vascularleptomeningealcell/vascularleptomeningealcell_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
vipGABA_gemma <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_false_from_gemma_true/ct_pseudobulks/gemma/vipGABAergiccorticalinterneuron/vipGABAergiccorticalinterneuron_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
```

```{r}
astrocyte_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Astro/Astro_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
chandelier_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Chandelier/Chandelier_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
endothelial_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Endo/Endo_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
immune_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Immune/Immune_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L2_3_IT_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/L2_3_IT/L2_3_IT_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L4_IT_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/L4_IT/L4_IT_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L5_6_NP_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/L5_6_NP/L5_6_NP_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L5_ET_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/L5_ET/L5_ET_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L5_IT_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/L5_IT/L5_IT_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L6_CT_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/L6_CT/L6_CT_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L6_IT_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/L6_IT/L6_IT_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L6_IT_car3_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/L6_IT_Car3/L6_IT_Car3_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
L6b_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/L6b/L6b_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
Lamp5_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Lamp5/Lamp5_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
Lamp5_Lhx6_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Lamp5_Lhx6/Lamp5_Lhx6_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
micro_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Micro/Micro_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
oligo_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Oligo/Oligo_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
oligoPC_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/OPC/OPC_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
Pax6_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Pax6/Pax6_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
PC_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/PC/PC_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
Pvalb_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Pvalb/Pvalb_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
SMC_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/SMC/SMC_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
sncg_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Sncg/Sncg_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
sst_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Sst/Sst_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
sst_chodl_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Sst_Chodl/Sst_Chodl_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
vip_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/Vip/Vip_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))
VLMC_author <- as.data.frame(read_tsv("/space/grp/rschwartz/rschwartz/psychENCODE-reanalysis/results_author_submitted_true_from_gemma_true/ct_pseudobulks/gemma/VLMC/VLMC_pseudobulk_matrix.tsv.gz", show_col_types = FALSE))


for (file in list.files(path = "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode.txt_author_true_sample_split_true/metadata/homo_sapiens", pattern = "*.tsv", full.names = TRUE)){
  
  object_name <- tools::file_path_sans_ext(basename(file))
  
  data <- read.delim(file, stringsAsFactors = FALSE, check.names = FALSE)
  assign(object_name, data, envir = .GlobalEnv)
rm (data)
}

Velmeshev_et_al.1_sample_meta$`organism part` <- NULL
Velmeshev_et_al.2_sample_meta$`organism part` <- NULL
dfs <-  c("CMC_sample_meta", "DevBrain_sample_meta", "MultiomeBrain_sample_meta", "PTSDBrainomics_sample_meta", "SZBDMulti-Seq_sample_meta", "UCLA-ASD_sample_meta","Velmeshev_et_al.1_sample_meta","Velmeshev_et_al.2_sample_meta")
df_list <- lapply(dfs, get)

metadata <- do.call(rbind, df_list)
colnames(metadata)[colnames(metadata) == "1000G_ancestry"] <- "Ancestry"
metadata$Age_death <- as.numeric(as.character(metadata$Age_death))
metadata$Disorder[metadata$Disorder == "control"] <- "Control"

```

```{r functions}
transposePCA <- function(data){
rownames(data) <- data[[1]]

data <- data[, -1]

data <- t(data)

return(data)
}

#transposing

gemma_objs <- ls(pattern = "_gemma")
gemma_objs <- gemma_objs[sapply(gemma_objs, function(x) is.data.frame(get(x)))]

for (obj_name in gemma_objs) {
  df <- get(obj_name)
  df <- transposePCA(df)
  assign(obj_name, df, envir = .GlobalEnv)
}

author_objs <- ls(pattern = "_author")
author_objs <- author_objs[sapply(author_objs, function(x) is.data.frame(get(x)))]

for (obj_name in author_objs) {
  df <- get(obj_name)
  df <- transposePCA(df)
  assign(obj_name, df, envir = .GlobalEnv)
}

#plotting


cleanup <- function(expr_data) {
  
  expr_data_name <- deparse(substitute(expr_data))
  cleaned_name <- paste0(expr_data_name, "_clean")

  
  rownames(metadata) <- metadata[["sample_name"]]
  common_samples <- intersect(rownames(expr_data), rownames(metadata))
  expr_matched <- expr_data[common_samples, , drop = FALSE]
  metadata_matched <- metadata[common_samples, , drop = FALSE]

  Library_size <- log2(rowSums(expr_matched) + 1)

  expr_log <- log2(expr_matched + 1)

  gene_sds <- apply(expr_log, 2, sd)
  expr_filtered <- expr_log[, gene_sds > 0, drop = FALSE]

  cleaned_obj <- list(
    expr_raw = expr_matched,
    expr_log = expr_log,
    expr_filtered = expr_filtered,
    metadata = metadata_matched,
    Library_size = Library_size,
    sample_ids = common_samples
  )
  class(cleaned_obj) <- "CleanedExprData"
assign(cleaned_name, cleaned_obj, envir = parent.frame())
  return(invisible(cleaned_obj))
}

runPCA <- function(cleaned_data) {

  expr_filtered <- cleaned_data$expr_filtered
  metadata <- cleaned_data$metadata
  Library_size <- cleaned_data$Library_size

  pca_result <- prcomp(expr_filtered, center = TRUE, scale. = TRUE)

  pca_scores <- as.data.frame(pca_result$x)
  pca_scores$Sample <- rownames(pca_scores)
  pca_scores$Library_size <- Library_size[rownames(pca_scores)]

  pca_scores <- cbind(pca_scores, metadata[rownames(pca_scores), , drop = FALSE])

  pca_output <- list(
    pca_scores = pca_scores,         
    pca_model = pca_result,          
    rotation = pca_result$rotation,  
    sdev = pca_result$sdev,          
    var_explained = pca_result$sdev^2 / sum(pca_result$sdev^2) 
  )
  class(pca_output) <- "PCAResult"

  return(pca_output)
}

pcaPlot <- function(pca_result, plotTitle, x_pc = 1, y_pc = 2) {
  pca_df <- pca_result$pca_scores

  x_pc_col <- paste0("PC", x_pc)
  y_pc_col <- paste0("PC", y_pc)

  plots <- lapply(c("Age_death", "Biological_Sex", "Ancestry", "Disorder", "Cohort", "Library_size"), function(col) {
    is_continuous <- is.numeric(pca_df[[col]])

    p <- ggplot(pca_df, aes(x = .data[[x_pc_col]], y = .data[[y_pc_col]], color = .data[[col]])) +
      geom_point(size = 1) +
      theme_minimal() +
      theme(legend.text = element_text(size = 8),
            legend.title = element_text(size = 9),
            legend.key.size = unit(0.4, "cm"),
            legend.spacing = unit(0.2, "cm"),
            legend.margin = margin(2, 2, 2, 2, "pt"))

    # Set custom legend title
    legend_title <- if (col == "Library_size") "Library size \n(Log2-transformed)" else col

    p <- p + labs(color = legend_title,
                  x = x_pc_col,
                  y = y_pc_col)

    if (is_continuous) {
      p <- p + scale_color_gradient(low = "blue", high = "red")
    } else {
      p <- p + scale_color_brewer(palette = "Set1")
    }

    return(p)
  })

  combined_plot <- wrap_plots(plots) +
    plot_layout(ncol = 2) +
    plot_annotation(title = plotTitle)

  return(combined_plot)
}


screePlot <- function(variance_percent, plotTitle = "Scree Plot") {
  library(ggplot2)

  # Ensure it's numeric
  variance_percent <- as.numeric(variance_percent)[1:10]

  # Create data frame
  scree_df <- data.frame(
    PC = paste0("PC", seq_along(variance_percent)),
    Variance = variance_percent,
    Cumulative = cumsum(variance_percent)
  )

  ggplot(scree_df, aes(x = seq_along(Variance), y = Variance)) +
    geom_line(color = "red", size = 1) +
    geom_point(color = "red", size = 2) +
    geom_text(aes(y = Variance, label = paste0(round(Variance, 3), "%")),
              vjust = -0.8, size = 3.5, color = "black") +
    theme_minimal() +
    labs(title = plotTitle,
         x = "Principal Component",
         y = "Variance Explained (%)") +
    scale_x_continuous(breaks = seq_along(variance_percent),
                       labels = paste0("PC", seq_along(variance_percent))) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
plotLoadingsByPC <- function(pca_output, title = "top 10 gene loadings by PC", pcs = 1:4, top_n = 10) {
  rotation <- as.data.frame(pca_output$rotation)
  rotation$feature <- rownames(rotation)
  
  rotation <- rotation[, c("feature", paste0("PC", pcs))]
  
  rotation_long <- reshape2::melt(rotation, id.vars = "feature", variable.name = "PC", value.name = "value")
  
  top_genes <- rotation_long %>%
    dplyr::group_by(PC) %>%
    dplyr::slice_max(order_by = abs(value), n = top_n, with_ties = FALSE) %>%
    dplyr::ungroup()

  # Set label offset
  offset <- 0.005

  ggplot(top_genes, aes(x = PC, y = value, fill = feature)) +
    geom_bar(stat = "identity", position = position_dodge(width = 0.8)) +
    geom_text(aes(label = feature,
                  y = ifelse(value >= 0, value - offset, value + offset)),
              position = position_dodge(width = 0.8), size = 3, hjust = 0.5) +
    labs(title = title,
         x = "Principal Component",
         y = "Loading Value") +
    theme_minimal() +
    coord_flip() +
    theme(legend.position = "none")
}



```

summary: cohort-specific effect in multiple cell types, particularly **microglia** and **OPCs**

**library size** correlated to PC1

outliers seem to be mostly **UCLA-ASD** samples and **male** samples?

slight cohort clustering across multiple cell types for **PC3&4**

```{r L5 comparison}
cleanup(L5_ET_author)
L5_ET_author_PCA <- runPCA(L5_ET_author_clean)

cleanup(L5_gemma)
L5_gemma_PCA <- runPCA(L5_gemma_clean)

pcaPlot(L5_ET_author_PCA, "L5_ET_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(L5_ET_author_PCA, "L5_ET_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(L5_ET_author_PCA, "L5_ET_author PCA", x_pc = 5, y_pc = 6)

pcaPlot(L5_gemma_PCA, "L5_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(L5_gemma_PCA, "L5_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(L5_gemma_PCA, "L5_gemma PCA", x_pc = 5, y_pc = 6)

plotLoadingsByPC(L5_ET_author_PCA, "Top 10 gene loadings by PC for L5 ET author annotations")
plotLoadingsByPC(L5_gemma_PCA, "Top 10 gene loadings by PC for L5 ET Gemma annotations")

screePlot(L5_ET_author_PCA$var_explained, "PCA scree of author-annotated L5 extratelencephalic projecting glutamatergic cortical neurons")
screePlot(L5_gemma_PCA$var_explained, "PCA scree of Gemma-annotated L5 extratelencephalic projecting glutamatergic cortical neurons")
```

```{r astrocyte_author}
cleanup(astrocyte_author)
astrocyte_author_PCA <- runPCA(astrocyte_author_clean)
pcaPlot(astrocyte_author_PCA, "astrocyte_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(astrocyte_author_PCA, "astrocyte_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(astrocyte_author_PCA, "astrocyte_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(astrocyte_author_PCA)
```
```{r astrocyte_gemma}
cleanup(astrocyte_gemma)
astrocyte_gemma_PCA <- runPCA(astrocyte_gemma_clean)
pcaPlot(astrocyte_gemma_PCA, "astrocyte_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(astrocyte_gemma_PCA, "astrocyte_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(astrocyte_gemma_PCA, "astrocyte_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(astrocyte_gemma_PCA)
```
```{r caudal_gemma}
cleanup(caudal_gemma)
caudal_gemma_PCA <- runPCA(caudal_gemma_clean)
pcaPlot(caudal_gemma_PCA, "caudal_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(caudal_gemma_PCA, "caudal_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(caudal_gemma_PCA, "caudal_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(caudal_gemma_PCA)
```
```{r chandelier_author}
cleanup(chandelier_author)
chandelier_author_PCA <- runPCA(chandelier_author_clean)
pcaPlot(chandelier_author_PCA, "chandelier_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(chandelier_author_PCA, "chandelier_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(chandelier_author_PCA, "chandelier_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(chandelier_author_PCA)
```
```{r chandelier_gemma}
cleanup(chandelier_gemma)
chandelier_gemma_PCA <- runPCA(chandelier_gemma_clean)
pcaPlot(chandelier_gemma_PCA, "chandelier_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(chandelier_gemma_PCA, "chandelier_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(chandelier_gemma_PCA, "chandelier_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(chandelier_gemma_PCA)
```
```{r endothelial_author}
cleanup(endothelial_author)
endothelial_author_PCA <- runPCA(endothelial_author_clean)
pcaPlot(endothelial_author_PCA, "endothelial_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(endothelial_author_PCA, "endothelial_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(endothelial_author_PCA, "endothelial_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(endothelial_author_PCA)
```
```{r endothelial_gemma}
cleanup(endothelial_gemma)
endothelial_gemma_PCA <- runPCA(endothelial_gemma_clean)
pcaPlot(endothelial_gemma_PCA, "endothelial_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(endothelial_gemma_PCA, "endothelial_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(endothelial_gemma_PCA, "endothelial_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(endothelial_gemma_PCA)
```
```{r immune_author}
cleanup(immune_author)
immune_author_PCA <- runPCA(immune_author_clean)
pcaPlot(immune_author_PCA, "immune_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(immune_author_PCA, "immune_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(immune_author_PCA, "immune_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(immune_author_PCA)
```
```{r L2_3_IT_author}
cleanup(L2_3_IT_author)
L2_3_IT_author_PCA <- runPCA(L2_3_IT_author_clean)
pcaPlot(L2_3_IT_author_PCA, "L2_3_IT_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(L2_3_IT_author_PCA, "L2_3_IT_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(L2_3_IT_author_PCA, "L2_3_IT_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L2_3_IT_author_PCA)
```
```{r L2_36_gemma}
cleanup(L2_36_gemma)
L2_36_gemma_PCA <- runPCA(L2_36_gemma_clean)
pcaPlot(L2_36_gemma_PCA, "L2_36_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(L2_36_gemma_PCA, "L2_36_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(L2_36_gemma_PCA, "L2_36_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L2_36_gemma_PCA)
```
```{r L4_IT_author}
cleanup(L4_IT_author)
L4_IT_author_PCA <- runPCA(L4_IT_author_clean)
pcaPlot(L4_IT_author_PCA, "L4_IT_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(L4_IT_author_PCA, "L4_IT_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(L4_IT_author_PCA, "L4_IT_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L4_IT_author_PCA)
```
```{r L5_6_NP_author}
cleanup(L5_6_NP_author)
L5_6_NP_author_PCA <- runPCA(L5_6_NP_author_clean)
pcaPlot(L5_6_NP_author_PCA, "L5_6_NP_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(L5_6_NP_author_PCA, "L5_6_NP_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(L5_6_NP_author_PCA, "L5_6_NP_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L5_6_NP_author_PCA)
```
```{r L5_ET_author}
cleanup(L5_ET_author)
L5_ET_author_PCA <- runPCA(L5_ET_author_clean)
pcaPlot(L5_ET_author_PCA, "L5_ET_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(L5_ET_author_PCA, "L5_ET_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(L5_ET_author_PCA, "L5_ET_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L5_ET_author_PCA)
```
```{r L5_gemma}
cleanup(L5_gemma)
L5_gemma_PCA <- runPCA(L5_gemma_clean)
pcaPlot(L5_gemma_PCA, "L5_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(L5_gemma_PCA, "L5_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(L5_gemma_PCA, "L5_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L5_gemma_PCA)
```
```{r L5_IT_author}
cleanup(L5_IT_author)
L5_IT_author_PCA <- runPCA(L5_IT_author_clean)
pcaPlot(L5_IT_author_PCA, "L5_IT_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(L5_IT_author_PCA, "L5_IT_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(L5_IT_author_PCA, "L5_IT_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L5_IT_author_PCA)
```
```{r L6_CT_author}
cleanup(L6_CT_author)
L6_CT_author_PCA <- runPCA(L6_CT_author_clean)
pcaPlot(L6_CT_author_PCA, "L6_CT_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(L6_CT_author_PCA, "L6_CT_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(L6_CT_author_PCA, "L6_CT_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L6_CT_author_PCA)
```
```{r L6_IT_author}
cleanup(L6_IT_author)
L6_IT_author_PCA <- runPCA(L6_IT_author_clean)
pcaPlot(L6_IT_author_PCA, "L6_IT_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(L6_IT_author_PCA, "L6_IT_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(L6_IT_author_PCA, "L6_IT_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L6_IT_author_PCA)
```
```{r L6_IT_car3_author}
cleanup(L6_IT_car3_author)
L6_IT_car3_author_PCA <- runPCA(L6_IT_car3_author_clean)
pcaPlot(L6_IT_car3_author_PCA, "L6_IT_car3_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(L6_IT_car3_author_PCA, "L6_IT_car3_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(L6_IT_car3_author_PCA, "L6_IT_car3_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L6_IT_car3_author_PCA)
```
```{r L6b_author}
cleanup(L6b_author)
L6b_author_PCA <- runPCA(L6b_author_clean)
pcaPlot(L6b_author_PCA, "L6b_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(L6b_author_PCA, "L6b_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(L6b_author_PCA, "L6b_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L6b_author_PCA)
```
```{r L6bGlut_gemma}
cleanup(L6bGlut_gemma)
L6bGlut_gemma_PCA <- runPCA(L6bGlut_gemma_clean)
pcaPlot(L6bGlut_gemma_PCA, "L6bGlut_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(L6bGlut_gemma_PCA, "L6bGlut_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(L6bGlut_gemma_PCA, "L6bGlut_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L6bGlut_gemma_PCA)
```
```{r L6CT_gemma}
cleanup(L6CT_gemma)
L6CT_gemma_PCA <- runPCA(L6CT_gemma_clean)
pcaPlot(L6CT_gemma_PCA, "L6CT_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(L6CT_gemma_PCA, "L6CT_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(L6CT_gemma_PCA, "L6CT_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(L6CT_gemma_PCA)
```
```{r Lamp5_author}
cleanup(Lamp5_author)
Lamp5_author_PCA <- runPCA(Lamp5_author_clean)
pcaPlot(Lamp5_author_PCA, "Lamp5_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(Lamp5_author_PCA, "Lamp5_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(Lamp5_author_PCA, "Lamp5_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(Lamp5_author_PCA)
```
```{r lamp5_gemma}
cleanup(lamp5_gemma)
lamp5_gemma_PCA <- runPCA(lamp5_gemma_clean)
pcaPlot(lamp5_gemma_PCA, "lamp5_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(lamp5_gemma_PCA, "lamp5_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(lamp5_gemma_PCA, "lamp5_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(lamp5_gemma_PCA)
```
```{r Lamp5_Lhx6_author}
cleanup(Lamp5_Lhx6_author)
Lamp5_Lhx6_author_PCA <- runPCA(Lamp5_Lhx6_author_clean)
pcaPlot(Lamp5_Lhx6_author_PCA, "Lamp5_Lhx6_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(Lamp5_Lhx6_author_PCA, "Lamp5_Lhx6_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(Lamp5_Lhx6_author_PCA, "Lamp5_Lhx6_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(Lamp5_Lhx6_author_PCA)
```
```{r micro_author}
cleanup(micro_author)
micro_author_PCA <- runPCA(micro_author_clean)
pcaPlot(micro_author_PCA, "micro_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(micro_author_PCA, "micro_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(micro_author_PCA, "micro_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(micro_author_PCA)
```
```{r microglia_gemma}
cleanup(microglia_gemma)
microglia_gemma_PCA <- runPCA(microglia_gemma_clean)
pcaPlot(microglia_gemma_PCA, "microglia_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(microglia_gemma_PCA, "microglia_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(microglia_gemma_PCA, "microglia_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(microglia_gemma_PCA)
```
```{r NPglut_gemma}
cleanup(NPglut_gemma)
NPglut_gemma_PCA <- runPCA(NPglut_gemma_clean)
pcaPlot(NPglut_gemma_PCA, "NPglut_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(NPglut_gemma_PCA, "NPglut_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(NPglut_gemma_PCA, "NPglut_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(NPglut_gemma_PCA)
```
```{r oligo_author}
cleanup(oligo_author)
oligo_author_PCA <- runPCA(oligo_author_clean)
pcaPlot(oligo_author_PCA, "oligo_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(oligo_author_PCA, "oligo_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(oligo_author_PCA, "oligo_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(oligo_author_PCA)
```
```{r oligo_gemma}
cleanup(oligo_gemma)
oligo_gemma_PCA <- runPCA(oligo_gemma_clean)
pcaPlot(oligo_gemma_PCA, "oligo_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(oligo_gemma_PCA, "oligo_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(oligo_gemma_PCA, "oligo_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(oligo_gemma_PCA)
```
```{r oligoPC_author}
cleanup(oligoPC_author)
oligoPC_author_PCA <- runPCA(oligoPC_author_clean)
pcaPlot(oligoPC_author_PCA, "oligoPC_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(oligoPC_author_PCA, "oligoPC_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(oligoPC_author_PCA, "oligoPC_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(oligoPC_author_PCA)
```
```{r oligoPC_gemma}
cleanup(oligoPC_gemma)
oligoPC_gemma_PCA <- runPCA(oligoPC_gemma_clean)
pcaPlot(oligoPC_gemma_PCA, "oligoPC_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(oligoPC_gemma_PCA, "oligoPC_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(oligoPC_gemma_PCA, "oligoPC_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(oligoPC_gemma_PCA)
```
```{r Pax6_author}
cleanup(Pax6_author)
Pax6_author_PCA <- runPCA(Pax6_author_clean)
pcaPlot(Pax6_author_PCA, "Pax6_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(Pax6_author_PCA, "Pax6_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(Pax6_author_PCA, "Pax6_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(Pax6_author_PCA)
```
```{r PC_author}
cleanup(PC_author)
PC_author_PCA <- runPCA(PC_author_clean)
pcaPlot(PC_author_PCA, "PC_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(PC_author_PCA, "PC_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(PC_author_PCA, "PC_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(PC_author_PCA)
```
```{r Pvalb_author}
cleanup(Pvalb_author)
Pvalb_author_PCA <- runPCA(Pvalb_author_clean)
pcaPlot(Pvalb_author_PCA, "Pvalb_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(Pvalb_author_PCA, "Pvalb_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(Pvalb_author_PCA, "Pvalb_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(Pvalb_author_PCA)
```
```{r pvalbGABA_gemma}
cleanup(pvalbGABA_gemma)
pvalbGABA_gemma_PCA <- runPCA(pvalbGABA_gemma_clean)
pcaPlot(pvalbGABA_gemma_PCA, "pvalbGABA_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(pvalbGABA_gemma_PCA, "pvalbGABA_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(pvalbGABA_gemma_PCA, "pvalbGABA_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(pvalbGABA_gemma_PCA)
```
```{r SMC_author}
cleanup(SMC_author)
SMC_author_PCA <- runPCA(SMC_author_clean)
pcaPlot(SMC_author_PCA, "SMC_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(SMC_author_PCA, "SMC_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(SMC_author_PCA, "SMC_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(SMC_author_PCA)
```
```{r sncg_author}
cleanup(sncg_author)
sncg_author_PCA <- runPCA(sncg_author_clean)
pcaPlot(sncg_author_PCA, "sncg_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(sncg_author_PCA, "sncg_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(sncg_author_PCA, "sncg_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(sncg_author_PCA)
```
```{r sncg_gemma}
cleanup(sncg_gemma)
sncg_gemma_PCA <- runPCA(sncg_gemma_clean)
pcaPlot(sncg_gemma_PCA, "sncg_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(sncg_gemma_PCA, "sncg_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(sncg_gemma_PCA, "sncg_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(sncg_gemma_PCA)
```
```{r sst_author}
cleanup(sst_author)
sst_author_PCA <- runPCA(sst_author_clean)
pcaPlot(sst_author_PCA, "sst_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(sst_author_PCA, "sst_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(sst_author_PCA, "sst_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(sst_author_PCA)
```
```{r sst_chodl_author}
cleanup(sst_chodl_author)
sst_chodl_author_PCA <- runPCA(sst_chodl_author_clean)
pcaPlot(sst_chodl_author_PCA, "sst_chodl_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(sst_chodl_author_PCA, "sst_chodl_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(sst_chodl_author_PCA, "sst_chodl_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(sst_chodl_author_PCA)
```
```{r sstGABA_gemma}
cleanup(sstGABA_gemma)
sstGABA_gemma_PCA <- runPCA(sstGABA_gemma_clean)
pcaPlot(sstGABA_gemma_PCA, "sstGABA_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(sstGABA_gemma_PCA, "sstGABA_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(sstGABA_gemma_PCA, "sstGABA_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(sstGABA_gemma_PCA)
```
```{r vip_author}
cleanup(vip_author)
vip_author_PCA <- runPCA(vip_author_clean)
pcaPlot(vip_author_PCA, "vip_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(vip_author_PCA, "vip_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(vip_author_PCA, "vip_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(vip_author_PCA)
```
```{r vipGABA_gemma}
cleanup(vipGABA_gemma)
vipGABA_gemma_PCA <- runPCA(vipGABA_gemma_clean)
pcaPlot(vipGABA_gemma_PCA, "vipGABA_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(vipGABA_gemma_PCA, "vipGABA_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(vipGABA_gemma_PCA, "vipGABA_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(vipGABA_gemma_PCA)
```
```{r VLMC_author}
cleanup(VLMC_author)
VLMC_author_PCA <- runPCA(VLMC_author_clean)
pcaPlot(VLMC_author_PCA, "VLMC_author PCA", x_pc = 1, y_pc = 2)
pcaPlot(VLMC_author_PCA, "VLMC_author PCA", x_pc = 3, y_pc = 4)
pcaPlot(VLMC_author_PCA, "VLMC_author PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(VLMC_author_PCA)
```
```{r VLMC_gemma}
cleanup(VLMC_gemma)
VLMC_gemma_PCA <- runPCA(VLMC_gemma_clean)
pcaPlot(VLMC_gemma_PCA, "VLMC_gemma PCA", x_pc = 1, y_pc = 2)
pcaPlot(VLMC_gemma_PCA, "VLMC_gemma PCA", x_pc = 3, y_pc = 4)
pcaPlot(VLMC_gemma_PCA, "VLMC_gemma PCA", x_pc = 5, y_pc = 6)
plotLoadingsByPC(VLMC_gemma_PCA)
```