---
output: 
  html_document: 
    fig_width: 10
---

```{r setup, include=FALSE, warning=FALSE}
library(tidyr)
library(ggplot2)
library(readr)
library(dplyr)
library(scales)
library(DT)
library(knitr)
library(purrr)
library(kableExtra)
```

```{r}
CMCAuthor <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode.txt_author_true_sample_split_true/cell_type_assignments/CMC.celltypes.tsv", show_col_types = FALSE))

CMCGemma <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode_author_false_sample_split_false/cell_type_assignments/CMC.celltypes.tsv", show_col_types = FALSE))

DevBrainAuthor <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode.txt_author_true_sample_split_true/cell_type_assignments/DevBrain.celltypes.tsv", show_col_types = FALSE))

DevBrainGemma <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode_author_false_sample_split_false/cell_type_assignments/DevBrain.celltypes.tsv", show_col_types = FALSE))

MultiBrainAuthor <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode.txt_author_true_sample_split_true/cell_type_assignments/MultiomeBrain.celltypes.tsv", show_col_types = FALSE))

MultiBrainGemma <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode_author_false_sample_split_false/cell_type_assignments/MultiomeBrain.celltypes.tsv", show_col_types = FALSE))

PTSDAuthor <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode.txt_author_true_sample_split_true/cell_type_assignments/PTSDBrainomics.celltypes.tsv", show_col_types = FALSE))

PTSDGemma <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode_author_false_sample_split_false/cell_type_assignments/PTSDBrainomics.celltypes.tsv", show_col_types = FALSE))

SZBDAuthor <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode.txt_author_true_sample_split_true/cell_type_assignments/SZBDMulti-Seq.celltypes.tsv", show_col_types = FALSE))

SZBDGemma <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode_author_false_sample_split_false/cell_type_assignments/SZBDMulti-Seq.celltypes.tsv", show_col_types = FALSE))

ASDAuthor <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode.txt_author_true_sample_split_true/cell_type_assignments/UCLA-ASD.celltypes.tsv", show_col_types = FALSE))

ASDGemma <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode_author_false_sample_split_false/cell_type_assignments/UCLA-ASD.celltypes.tsv", show_col_types = FALSE))

Vel1Author <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode.txt_author_true_sample_split_true/cell_type_assignments/Velmeshev_et_al.1.celltypes.tsv", show_col_types = FALSE))

Vel1Gemma <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode_author_false_sample_split_false/cell_type_assignments/Velmeshev_et_al.1.celltypes.tsv", show_col_types = FALSE))

Vel2Author <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode.txt_author_true_sample_split_true/cell_type_assignments/Velmeshev_et_al.2.celltypes.tsv", show_col_types = FALSE))

Vel2Gemma <- data.frame(read_tsv(
  "/space/grp/rschwartz/rschwartz/get_gemma_data.nf/psychEncode_author_false_sample_split_false/cell_type_assignments/Velmeshev_et_al.2.celltypes.tsv", show_col_types = FALSE))

cellTypeMap <- data.frame(read_tsv("~/ProjectLB/psychENCODE-reanalysis/summary_statistics/cellTypeMapping.tsv", show_col_types = FALSE))

GemmaLabels <- data.frame(read_tsv("~/ProjectLB/psychENCODE-reanalysis/summary_statistics/GemmaLabels.tsv", show_col_types = FALSE))

map_author <- cellTypeMap %>%
  select(author_cell_type, subclass, class, family) %>%
  distinct()

map_gemma <- cellTypeMap %>%
  select(gemma_cell_type, subclass, class, family) %>%
  distinct()

```

```{r functions}

#merges gemma and author annotations based on cell id and reorganizes columns for clarity
cellTypeMapping <- function(dfName, author, gemma){
  
  newdf <- left_join(author, gemma, by = "cell_id")
  newdf <- newdf %>% 
    select(-sample_id.x,-sample_id.y, -cell_type_uri.x) %>% 
  rename(
    author_cell_type = cell_type.x, 
    gemma_cell_type = cell_type.y, 
    gemma_cell_type_uri = cell_type_uri.y )
  
  newdf <- merge(newdf, GemmaLabels, by.x = "gemma_cell_type", by.y = "gemma_cell_type", all.x = TRUE)
  newdf <- merge(newdf, cellTypeMap, by.x = "author_cell_type", by.y = "author_cell_type", all.x = TRUE)%>%
  rename( 
    gemma_cell_type_map = gemma_cell_type.y,
    gemma_cell_type = gemma_cell_type.x )
  newdf <- newdf %>% 
    select(-subclass, -class, -family)
    assign(dfName, newdf, envir = .GlobalEnv)
}

#counts number of gemma annotations mapped to each author annotation. n is the count of a gemma annotation mapped to an author annotation
countSummary <- function(alldf){
  
  alldf %>%
   dplyr::count(gemma_abbr, author_cell_type) %>%
  relocate(author_cell_type, .before = everything()) %>%
  arrange(author_cell_type)
}

addPercentages <- function(countdf){
  countdf %>%
  group_by(author_cell_type) %>%
  mutate(percentage = round(n / sum(n) * 100, 2))
}



```

```{r plot functions}

plotPalette <- c("#ef6489","#d2422e","#925542","#d77d4f","#d9a33d","#847d33","#cdc698","#ccd44b","#7ada45","#4e9042","#556d51","#77dc90","#78ccbf","#86b2d8","#536783","#6e6ac8","#843cd9","#cc4fc0","#894b7b","#d5a0c2")

#plots count of each cell type
cellCountPlot <- function(df, plotTitle, type_col, angle, xlim){
  
  ggplot(df, aes(x = type_col, fill = type_col)) +
  geom_bar() +
  geom_text(stat = "count",
            aes(label= ..count..), 
            hjust= -0.1, 
            color = "black", 
            size = 3.5,) +
  coord_flip() +
  labs(
    title = plotTitle,
    x = "cell types",
    y = "Count") +
    scale_y_continuous(
      limits = c(0, xlim),
      labels = label_comma(),
      expand = expansion(mult = c(0, 0.05)))+
     theme(plot.title = element_text(size = 12, hjust = 0.5),
        legend.position = "none")
}

#stacked plot for grouping gemma annotations to author annotations
stackPlot <- function(countdf, group_col, fill_col,plotTitle, xlim){
  
  group_col <- rlang::sym(group_col)
  fill_col <- rlang::sym(fill_col)
  
  bar_data <- countdf %>%
    group_by(!!group_col, !!fill_col, name = "count")
  
  totals <- bar_data %>%
    group_by(!!group_col) %>%
    summarise(total = sum(n), .groups = "drop")
  
  ggplot(countdf, aes(x = !!group_col, y = n, fill = !!fill_col)) +
  geom_bar(stat = "identity",
           position = "stack")+
    geom_text(data = totals,
              aes(x = !!group_col, y = total, label = total),
              hjust = -0.1,
              size = 3.5,
              inherit.aes = FALSE) +
  coord_flip() +
    scale_fill_manual(values = plotPalette) +
    scale_y_continuous(limits = c(0, xlim), 
                       labels = label_comma(),
                       expand = expansion(mult = c(0,0.07))) +
  labs(title = plotTitle,
       x = "Author annotations",
       y = "Count",
       fill = "Gemma annotations")
}


checkMatch <- function(dfname, alldf){

newdf <- alldf %>%
  left_join(map_author, by = "author_cell_type", relationship = "many-to-many") %>%
  left_join(map_gemma, by = "gemma_cell_type", suffix = c("", "_gemma"), relationship = "many-to-many") %>%
  rename_with(~paste0(., "_author"), c("subclass", "class", "family"))

#returns true match if Immune matches with gemma annotation at family level and if SMC at class level
newdf <- newdf %>%
  mutate(match_flag = case_when(
    author_cell_type == "Immune" ~ family_author == family_gemma,
    author_cell_type == "SMC" ~ class_author == class_gemma,
    TRUE ~ subclass_author == subclass_gemma
  ))
assign(dfname, newdf, envir = .GlobalEnv)
}

matchCount <- function(data) {
  data %>%
    filter(!is.na(match_flag)) %>%  
     #mutate(match_flag = ifelse(match_flag, "TRUE", "FALSE")) %>%
    group_by(author_cell_type, match_flag) %>%
    summarise(count = n(), .groups = "drop") %>%
    pivot_wider(
      names_from = match_flag,
      values_from = count,
      values_fill = 0
    )
}

matchPlot <- function(df, plot_type = c("count", "percentage"), xlim){
  
  plot_type <- match.arg(plot_type)
  
  df_clean <- df %>% filter(!is.na(match_flag))
  
  counts <- df_clean %>%
    group_by(author_cell_type, match_flag) %>%
    summarise(count = n(), .groups = 'drop') %>%
    complete(author_cell_type, match_flag, fill = list(count = 0))
  
  if (plot_type == "percentage") {
    counts <- counts %>%
      group_by(author_cell_type) %>%
      mutate(percentage = count / sum(count) * 100) %>%
      ungroup()
    
    ggplot(counts, aes(x = author_cell_type, y = percentage, fill = factor(match_flag))) +
      geom_bar(stat = "identity") +
      coord_flip() +
      labs(
        x = "Author annotations",
        y = "Percentage",
        title = "Percentage of of correct Gemma cell annotations"
      ) +
      theme(legend.title=element_blank())+
      scale_y_continuous(expand = c(0, 0), labels = label_comma(),) +
      scale_fill_manual(values = c("FALSE" = "#d62728", "TRUE" = "#2ca02c"))
    
  } else {
    ggplot(counts, aes(x = author_cell_type, y = count, fill = factor(match_flag))) +
      geom_bar(stat = "identity") +
      coord_flip() +
      labs(
        x = "Author annotations",
        y = "Count",
        title = "Counts of correct Gemma cell annotations"
      ) +
      theme(legend.title=element_blank())+
      scale_y_continuous(limits = c(0, xlim), labels = label_comma(),expand = expansion(mult = c(0,0.07))) +
      scale_fill_manual(values = c("FALSE" = "#d62728", "TRUE" = "#2ca02c"))
  }
}
percentPlot <- function(countdf, plotTitle){

  ggplot(countdf, aes(x = factor(author_cell_type), y = percentage, fill = gemma_abbr)) +
  geom_bar(stat = "identity") +
   coord_flip() +
  labs(title = plotTitle,
       x = "Author annotations",
       y = "Percentage",
       hjust = 1,
       fill = "Gemma Annotations") +
    scale_fill_manual(values = plotPalette) +
    scale_y_continuous(expand = c(0, 0))
}

#makes summary table with summary_col specified as either count or percent column
tableSummary <- function(df, summary_col){
  
 col_sym <- sym(summary_col)

  # COUNT TABLE
  count_tbl <- df %>%
    group_by(author_cell_type, gemma_abbr) %>%
    summarise(N = sum(!!col_sym), .groups = "drop") %>%
    pivot_wider(names_from = gemma_abbr, values_from = N, values_fill = list(N = 0)) %>%
    arrange(author_cell_type)
}



```

# Counts of Gemma cell type annotations vs. author cell type annotations

## CMC

```{r cmc}

cellTypeMapping("CMCAll", CMCAuthor, CMCGemma)

CMCCount <- countSummary(CMCAll)

CMCPercent <- addPercentages(CMCCount)

checkMatch("CMCMapped", CMCAll)

#plots below

cellCountPlot(CMCAll, "CMC Gemma Annotations", CMCAll$gemma_abbr, 20, 200500) 

cellCountPlot(CMCAll, "CMC Author Annotations", CMCAll$author_cell_type, 45, 200500)

stackPlot(CMCCount,"author_cell_type", "gemma_abbr", " CMC Gemma annotations mapped to author annotations", 100100)

matchPlot(CMCMapped, plot_type = "count", 100000)

matchPlot(CMCMapped, plot_type = "percent")

CMCCountTable <- tableSummary(CMCPercent, summary_col = "n")
datatable(CMCCountTable, caption = "Counts of each Gemma annotation mapped to author annotations")
CMCPercentTable <- tableSummary(CMCPercent, summary_col = "percentage")
datatable(CMCPercentTable, caption = "Percentages of each Gemma annotation mapped to author annotations")
CMCMatchTable <- matchCount(CMCMapped)
datatable(CMCMatchTable, caption = "Counts of correct and incorrect Gemma annotations")

```
```{r devbrain}

cellTypeMapping("DevBrainAll", DevBrainAuthor, DevBrainGemma)

DevBrainCount <- countSummary(DevBrainAll)

DevBrainPercent <- addPercentages(DevBrainCount)

checkMatch("DevBrainMapped", DevBrainAll)

#plots below

cellCountPlot(DevBrainAll, "DevBrain Gemma Annotations", DevBrainAll$gemma_abbr, 20, 40000) 

cellCountPlot(DevBrainAll, "DevBrain Author Annotations", DevBrainAll$author_cell_type, 45, 40000)

stackPlot(DevBrainCount,"author_cell_type", "gemma_abbr", " DevBrain Gemma annotations mapped to author annotations", 18000)

matchPlot(DevBrainMapped, plot_type = "count", 18000)

matchPlot(DevBrainMapped, plot_type = "percent")

DevBrainCountTable <- tableSummary(DevBrainPercent, summary_col = "n")
datatable(DevBrainCountTable, caption = "Counts of each Gemma annotation mapped to author annotations")
DevBrainPercentTable <- tableSummary(DevBrainPercent, summary_col = "percentage")
datatable(DevBrainPercentTable, caption = "Percentages of each Gemma annotation mapped to author annotations")
DevBrainMatchTable <- matchCount(DevBrainMapped)
datatable(DevBrainMatchTable, caption = "Counts of correct and incorrect Gemma annotations")

```
```{r MultiBrain}

cellTypeMapping("MultiBrainAll", MultiBrainAuthor, MultiBrainGemma)

MultiBrainCount <- countSummary(MultiBrainAll)

MultiBrainPercent <- addPercentages(MultiBrainCount)

checkMatch("MultiBrainMapped", MultiBrainAll)

#plots below

cellCountPlot(MultiBrainAll, "MultiBrain Gemma Annotations", MultiBrainAll$gemma_abbr, 20, 45000) 

cellCountPlot(MultiBrainAll, "MultiBrain Author Annotations", MultiBrainAll$author_cell_type, 45, 45000)

stackPlot(MultiBrainCount,"author_cell_type", "gemma_abbr", " MultiBrain Gemma annotations mapped to author annotations", 40000)

matchPlot(MultiBrainMapped, plot_type = "count", 40000)

matchPlot(MultiBrainMapped, plot_type = "percent")

MultiBrainCountTable <- tableSummary(MultiBrainPercent, summary_col = "n")
datatable(MultiBrainCountTable, caption = "Counts of each Gemma annotation mapped to author annotations")
MultiBrainPercentTable <- tableSummary(MultiBrainPercent, summary_col = "percentage")
datatable(MultiBrainPercentTable, caption = "Percentages of each Gemma annotation mapped to author annotations")
MultiBrainMatchTable <- matchCount(MultiBrainMapped)
datatable(MultiBrainMatchTable, caption = "Counts of correct and incorrect Gemma annotations")

```
```{r PTSD}

cellTypeMapping("PTSDAll", PTSDAuthor, PTSDGemma)

PTSDCount <- countSummary(PTSDAll)

PTSDPercent <- addPercentages(PTSDCount)

checkMatch("PTSDMapped", PTSDAll)

#plots below

cellCountPlot(PTSDAll, "PTSD Gemma Annotations", PTSDAll$gemma_abbr, 20, 82000) 

cellCountPlot(PTSDAll, "PTSD Author Annotations", PTSDAll$author_cell_type, 45, 82000)

stackPlot(PTSDCount,"author_cell_type", "gemma_abbr", " PTSD Gemma annotations mapped to author annotations", 50000)

matchPlot(PTSDMapped, plot_type = "count", 50000)

matchPlot(PTSDMapped, plot_type = "percent")

PTSDCountTable <- tableSummary(PTSDPercent, summary_col = "n")
datatable(PTSDCountTable, caption = "Counts of each Gemma annotation mapped to author annotations")
PTSDPercentTable <- tableSummary(PTSDPercent, summary_col = "percentage")
datatable(PTSDPercentTable, caption = "Percentages of each Gemma annotation mapped to author annotations")
PTSDMatchTable <- matchCount(PTSDMapped)
datatable(PTSDMatchTable, caption = "Counts of correct and incorrect Gemma annotations")
```
```{r SZBD}

cellTypeMapping("SZBDAll", SZBDAuthor, SZBDGemma)

SZBDCount <- countSummary(SZBDAll)

SZBDPercent <- addPercentages(SZBDCount)

checkMatch("SZBDMapped", SZBDAll)

#plots below

cellCountPlot(SZBDAll, "SZBD Gemma Annotations", SZBDAll$gemma_abbr, 20, 350000) 

cellCountPlot(SZBDAll, "SZBD Author Annotations", SZBDAll$author_cell_type, 45, 350000)

stackPlot(SZBDCount,"author_cell_type", "gemma_abbr", " SZBD Gemma annotations mapped to author annotations", 180000)

matchPlot(SZBDMapped, plot_type = "count", 180000)

matchPlot(SZBDMapped, plot_type = "percent")

SZBDCountTable <- tableSummary(SZBDPercent, summary_col = "n")
datatable(SZBDCountTable, caption = "Counts of each Gemma annotation mapped to author annotations")
SZBDPercentTable <- tableSummary(SZBDPercent, summary_col = "percentage")
datatable(SZBDPercentTable, caption = "Percentages of each Gemma annotation mapped to author annotations")
SZBDMatchTable <- matchCount(SZBDMapped)
datatable(SZBDMatchTable, caption = "Counts of correct and incorrect Gemma annotations")

```
```{r ASD}

cellTypeMapping("ASDAll", ASDAuthor, ASDGemma)

ASDCount <- countSummary(ASDAll)

ASDPercent <- addPercentages(ASDCount)

checkMatch("ASDMapped", ASDAll)

#plots below

cellCountPlot(ASDAll, "ASD Gemma Annotations", ASDAll$gemma_abbr, 20, 170000) 

cellCountPlot(ASDAll, "ASD Author Annotations", ASDAll$author_cell_type, 45, 170000)

stackPlot(ASDCount,"author_cell_type", "gemma_abbr", " ASD Gemma annotations mapped to author annotations", 90000)

matchPlot(ASDMapped, plot_type = "count", 90000)

matchPlot(ASDMapped, plot_type = "percent")

ASDCountTable <- tableSummary(ASDPercent, summary_col = "n")
datatable(ASDCountTable, caption = "Counts of each Gemma annotation mapped to author annotations")
ASDPercentTable <- tableSummary(ASDPercent, summary_col = "percentage")
datatable(ASDPercentTable, caption = "Percentages of each Gemma annotation mapped to author annotations")
ASDMatchTable <- matchCount(ASDMapped)
datatable(ASDMatchTable, caption = "Counts of correct and incorrect Gemma annotations")
```
```{r Vel1}

cellTypeMapping("Vel1All", Vel1Author, Vel1Gemma)

Vel1Count <- countSummary(Vel1All)

Vel1Percent <- addPercentages(Vel1Count)

checkMatch("Vel1Mapped", Vel1All)

#plots below

cellCountPlot(Vel1All, "Vel1 Gemma Annotations", Vel1All$gemma_abbr, 20, 5500) 

cellCountPlot(Vel1All, "Vel1 Author Annotations", Vel1All$author_cell_type, 45, 5500)

stackPlot(Vel1Count,"author_cell_type", "gemma_abbr", " Vel1 Gemma annotations mapped to author annotations", 5500)

matchPlot(Vel1Mapped, plot_type = "count", 5500)

matchPlot(Vel1Mapped, plot_type = "percent")

Vel1CountTable <- tableSummary(Vel1Percent, summary_col = "n")
datatable(Vel1CountTable, caption = "Counts of each Gemma annotation mapped to author annotations")
Vel1PercentTable <- tableSummary(Vel1Percent, summary_col = "percentage")
datatable(Vel1PercentTable, caption = "Percentages of each Gemma annotation mapped to author annotations")
Vel1MatchTable <- matchCount(Vel1Mapped)
datatable(Vel1MatchTable, caption = "Counts of correct and incorrect Gemma annotations")
```
```{r Vel2}

cellTypeMapping("Vel2All", Vel2Author, Vel2Gemma)

Vel2Count <- countSummary(Vel2All)

Vel2Percent <- addPercentages(Vel2Count)

checkMatch("Vel2Mapped", Vel2All)

#plots below

cellCountPlot(Vel2All, "Vel2 Gemma Annotations", Vel2All$gemma_abbr, 20, 15000) 

cellCountPlot(Vel2All, "Vel2 Author Annotations", Vel2All$author_cell_type, 45, 15000)

stackPlot(Vel2Count,"author_cell_type", "gemma_abbr", " Vel2 Gemma annotations mapped to author annotations", 8000)

matchPlot(Vel2Mapped, plot_type = "count", 8000)

matchPlot(Vel2Mapped, plot_type = "percent")

Vel2CountTable <- tableSummary(Vel2Percent, summary_col = "n")
datatable(Vel2CountTable, caption = "Counts of each Gemma annotation mapped to author annotations")
Vel2PercentTable <- tableSummary(Vel2Percent, summary_col = "percentage")
datatable(Vel2PercentTable, caption = "Percentages of each Gemma annotation mapped to author annotations")
Vel2MatchTable <- matchCount(Vel2Mapped)
datatable(Vel2MatchTable, caption = "Counts of correct and incorrect Gemma annotations")

```
```{r all}

CMCAll$Source <- "CMC"
DevBrainAll$Source <- "DevBrain"
MultiBrainAll$Source <- "MultiBrain"
PTSDAll$Source <- "PTSD"
ASDAll$Source <- "ASD"
SZBDAll$Source <- "SZBD"
Vel1All$Source <- "Vel1"
Vel2All$Source <- "Vel2"

PsychEncodeAll <- rbind(CMCAll, DevBrainAll, MultiBrainAll, PTSDAll, SZBDAll, ASDAll, Vel1All, Vel2All)

PsychEncodeCount <- countSummary(PsychEncodeAll)

PsychEncodePercent <- addPercentages(PsychEncodeCount)

checkMatch("PsychEncodeMapped", PsychEncodeAll)

#plots below

cellCountPlot(PsychEncodeAll, "PsychEncode Gemma Annotations", PsychEncodeAll$gemma_abbr, 20, 900000) 

cellCountPlot(PsychEncodeAll, "PsychEncode Author Annotations", PsychEncodeAll$author_cell_type, 45, 900000)

stackPlot(PsychEncodeCount,"author_cell_type", "gemma_abbr", " PsychEncode Gemma annotations mapped to author annotations", 500000)

matchPlot(PsychEncodeMapped, plot_type = "count", 450000)

matchPlot(PsychEncodeMapped, plot_type = "percent")

PsychEncodeCountTable <- tableSummary(PsychEncodeCount, summary_col = "n")
datatable(PsychEncodeCountTable, caption = "Counts of each Gemma annotation mapped to author annotations")
PsychEncodePercentTable <- tableSummary(PsychEncodePercent, summary_col = "percentage")
datatable(PsychEncodePercentTable, caption = "Percentages of each Gemma annotation mapped to author annotations")
PsychEncodeMatchTable <- matchCount(PsychEncodeMapped)
datatable(PsychEncodeMatchTable, caption = "Counts of correct and incorrect Gemma annotations")
```